name: Go Gin 自动部署

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: 编译项目
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o gin-web main.go

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /root/gin-web
            echo "开始部署"
            git pull
            CGO_ENABLED=0 GOOS=linux go build -o gin-web main.go
            echo "启动服务"
            ( ./gin-web > app.log 2>&1 & )
            sleep 2
            echo "部署完成！"